### ISSUE TITLE
Add how to add app, service and template explanation

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/awesome#1]
Add a contribution guide / pr template / in the README explanation on how to add application, services and template and how to run the script to generate the README.md
Will be nice until we have the form on the website.

**Comment by antho1404** [comment]
List of things we need to explain in the contribution guide:
- [ ] How to add a new service (fork the project, add your service in the `services.json` file, generate the new readme with `node script/generateReadme.md`, create a pull request with the modifications)
- [ ] How to add a new application (fork the project, add your application in the `applications.json` file, generate the new readme with `node script/generateReadme.md`, create a pull request with the modifications)
- [ ] Onboard new user with a list of existing services example that they can implement based on issues here that can be accessible with https://github.com/mesg-foundation/awesome/issues?q=is%3Aissue+is%3Aopen+label%3Aservice
- [ ] Explain that if they want a new service they can create a new issue here https://github.com/mesg-foundation/awesome/issues/new with the detail of the service, a description and why it's useful, also add the `service` label
- [ ] Redirect them to all the resources discord (available for help), docs and tutorials
- [ ] If there is any bugs related to the core they can submit a bug issue here http://github.com/mesg-foundation/core/issues

**Comment by antho1404** [comment]
Need to change this, we simplified the process and only editing the readme file is enought now
